// FBS Teams data for reconstructing team details from minimal saved data
// This is populated from the same source as the client-side data

exports.fbsTeamsMap = {
  "Air Force Academy": { schoolName: "Air Force Academy", teamName: "Falcons", location: "Colorado Springs, CO", conference: "Mountain West" },
  "University of Akron": { schoolName: "University of Akron", teamName: "Zips", location: "Akron, OH", conference: "MAC" },
  "University of Alabama": { schoolName: "University of Alabama", teamName: "Crimson Tide", location: "Tuscaloosa, AL", conference: "SEC" },
  "University of Alabama at Birmingham": { schoolName: "University of Alabama at Birmingham", teamName: "Blazers", location: "Birmingham, AL", conference: "AAC" },
  "University of New Mexico": { teamName: "Lobos", location: "Albuquerque, NM", conference: "Mountain West" },
  "Arizona State University": { teamName: "Sun Devils", location: "Tempe, AZ", conference: "Big 12" },
  "University of Arizona": { teamName: "Wildcats", location: "Tucson, AZ", conference: "Big 12" },
  "Arkansas State University": { teamName: "Red Wolves", location: "Jonesboro, AR", conference: "Sun Belt" },
  "University of Arkansas": { teamName: "Razorbacks", location: "Fayetteville, AR", conference: "SEC" },
  "United States Military Academy": { teamName: "Cadets", location: "West Point, NY", conference: "AAC" },
  "Auburn University": { teamName: "Tigers", location: "Auburn, AL", conference: "SEC" },
  "Ball State University": { teamName: "Cardinals", location: "Muncie, IN", conference: "MAC" },
  "Baylor University": { teamName: "Bears", location: "Waco, TX", conference: "Big 12" },
  "Boise State University": { teamName: "Broncos", location: "Boise, ID", conference: "Mountain West" },
  "Boston College": { teamName: "Eagles", location: "Chestnut Hill, MA", conference: "ACC" },
  "Bowling Green State University": { teamName: "Falcons", location: "Bowling Green, OH", conference: "MAC" },
  "University at Buffalo": { teamName: "Bulls", location: "Buffalo, NY", conference: "MAC" },
  "Brigham Young University": { teamName: "Cougars", location: "Provo, UT", conference: "Big 12" },
  "University of California, Berkeley": { teamName: "Golden Bears", location: "Berkeley, CA", conference: "ACC" },
  "University of California, Los Angeles": { teamName: "Bruins", location: "Los Angeles, CA", conference: "Big Ten" },
  "Central Michigan University": { teamName: "Chippewas", location: "Mount Pleasant, MI", conference: "MAC" },
  "University of Cincinnati": { teamName: "Bearcats", location: "Cincinnati, OH", conference: "Big 12" },
  "Coastal Carolina University": { teamName: "Chanticleers", location: "Conway, SC", conference: "Sun Belt" },
  "University of Colorado Boulder": { teamName: "Buffaloes", location: "Boulder, CO", conference: "Big 12" },
  "University of Connecticut": { teamName: "Huskies", location: "Storrs, CT", conference: "Independent" },
  "DePaul University": { teamName: "Blue Demons", location: "Chicago, IL", conference: "Big East" },
  "Duke University": { teamName: "Blue Devils", location: "Durham, NC", conference: "ACC" },
  "East Carolina University": { teamName: "Pirates", location: "Greenville, NC", conference: "AAC" },
  "San Jose State University": { teamName: "Spartans", location: "San Jose, CA", conference: "Mountain West" },
  "Eastern Michigan University": { teamName: "Eagles", location: "Ypsilanti, MI", conference: "MAC" },
  "Florida State University": { teamName: "Seminoles", location: "Tallahassee, FL", conference: "ACC" },
  "Florida Atlantic University": { teamName: "Owls", location: "Boca Raton, FL", conference: "AAC" },
  "University of Florida": { teamName: "Gators", location: "Gainesville, FL", conference: "SEC" },
  "Fresno State University": { teamName: "Bulldogs", location: "Fresno, CA", conference: "Mountain West" },
  "Georgia State University": { teamName: "Panthers", location: "Atlanta, GA", conference: "Sun Belt" },
  "Georgia Tech": { teamName: "Yellow Jackets", location: "Atlanta, GA", conference: "ACC" },
  "University of Georgia": { teamName: "Bulldogs", location: "Athens, GA", conference: "SEC" },
  "University of Hawaii at Manoa": { teamName: "Rainbow Warriors", location: "Honolulu, HI", conference: "Mountain West" },
  "University of Houston": { teamName: "Cougars", location: "Houston, TX", conference: "Big 12" }
  // Add more teams as needed to cover all possible schools
};