export interface FCSTeam {
  teamName: string;
  schoolName: string;
  location: string;
  conference: string;
}

export const fcsTeams: FCSTeam[] = [
  { teamName: "Wildcats", schoolName: "Abilene Christian University", location: "Abilene, Texas", conference: "UAC" },
  { teamName: "Bulldogs", schoolName: "Alabama A&M University", location: "Normal, Alabama", conference: "SWAC" },
  { teamName: "Hornets", schoolName: "Alabama State University", location: "Montgomery, Alabama", conference: "SWAC" },
  { teamName: "Great Danes", schoolName: "University at Albany", location: "Albany, New York", conference: "CAA" },
  { teamName: "Sycamores", schoolName: "Indiana State University", location: "Terre Haute, Indiana", conference: "MVFC" },
  { teamName: "Lumberjacks", schoolName: "Northern Arizona University", location: "Flagstaff, Arizona", conference: "Big Sky" },
  { teamName: "Braves", schoolName: "Alcorn State University", location: "Lorman, Mississippi", conference: "SWAC" },
  { teamName: "Leopards", schoolName: "Lafayette College", location: "Easton, Pennsylvania", conference: "Patriot" },
  { teamName: "Mountain Hawks", schoolName: "Lehigh University", location: "Bethlehem, Pennsylvania", conference: "Patriot" },
  { teamName: "Bison", schoolName: "Howard University", location: "Washington, D.C.", conference: "MEAC" },
  { teamName: "Mountaineers", schoolName: "Appalachian State University", location: "Boone, North Carolina", conference: "Sun Belt" },
  { teamName: "River Hawks", schoolName: "UMass Lowell", location: "Lowell, Massachusetts", conference: "CAA" },
  { teamName: "Wildcats", schoolName: "Arizona State University", location: "Tempe, Arizona", conference: "Big Sky" },
  { teamName: "Red Wolves", schoolName: "Arkansas State University", location: "Jonesboro, Arkansas", conference: "Sun Belt" },
  { teamName: "Bears", schoolName: "University of Central Arkansas", location: "Conway, Arkansas", conference: "UAC" },
  { teamName: "Owls", schoolName: "Florida Atlantic University", location: "Boca Raton, Florida", conference: "C-USA" },
  { teamName: "Governors", schoolName: "Austin Peay State University", location: "Clarksville, Tennessee", conference: "UAC" },
  { teamName: "Wildcats", schoolName: "Bethune-Cookman University", location: "Daytona Beach, Florida", conference: "SWAC" },
  { teamName: "Bison", schoolName: "Bucknell University", location: "Lewisburg, Pennsylvania", conference: "Patriot" },
  { teamName: "Bulldogs", schoolName: "Butler University", location: "Indianapolis, Indiana", conference: "Pioneer" },
  { teamName: "Golden Bears", schoolName: "University of California, Berkeley", location: "Berkeley, California", conference: "Pac-12" },
  { teamName: "Aggies", schoolName: "University of California, Davis", location: "Davis, California", conference: "Big Sky" },
  { teamName: "Fighting Hawks", schoolName: "University of North Dakota", location: "Grand Forks, North Dakota", conference: "MVFC" },
  { teamName: "Campbell Camels", schoolName: "Campbell University", location: "Buies Creek, North Carolina", conference: "CAA" },
  { teamName: "Chippewas", schoolName: "Central Michigan University", location: "Mount Pleasant, Michigan", conference: "MAC" },
  { teamName: "Chanticleers", schoolName: "Coastal Carolina University", location: "Conway, South Carolina", conference: "Sun Belt" },
  { teamName: "Buccaneers", schoolName: "Charleston Southern University", location: "Charleston, South Carolina", conference: "Big South" },
  { teamName: "Keydets", schoolName: "Virginia Military Institute", location: "Lexington, Virginia", conference: "SoCon" },
  { teamName: "Tigers", schoolName: "Jackson State University", location: "Jackson, Mississippi", conference: "SWAC" },
  { teamName: "Blue Hens", schoolName: "University of Delaware", location: "Newark, Delaware", conference: "CAA" },
  { teamName: "Wildcats", schoolName: "Davidson College", location: "Davidson, North Carolina", conference: "Pioneer" },
  { teamName: "Blue Devils", schoolName: "Central Connecticut State University", location: "New Britain, Connecticut", conference: "NEC" },
  { teamName: "Pioneers", schoolName: "University of Denver", location: "Denver, Colorado", conference: "Summit" },
  { teamName: "Dukes", schoolName: "Duquesne University", location: "Pittsburgh, Pennsylvania", conference: "NEC" },
  { teamName: "Pirates", schoolName: "Eastern Carolina University", location: "Greenville, North Carolina", conference: "AAC" },
  { teamName: "Eagles", schoolName: "Eastern Washington University", location: "Cheney, Washington", conference: "Big Sky" },
  { teamName: "Colonels", schoolName: "Eastern Kentucky University", location: "Richmond, Kentucky", conference: "UAC" },
  { teamName: "Panthers", schoolName: "Eastern Illinois University", location: "Charleston, Illinois", conference: "OVC" },
  { teamName: "Colonels", schoolName: "Nicholls State University", location: "Thibodaux, Louisiana", conference: "Southland" },
  { teamName: "Lions", schoolName: "Florida A&M University", location: "Tallahassee, Florida", conference: "SWAC" },
  { teamName: "Flames", schoolName: "Liberty University", location: "Lynchburg, Virginia", conference: "C-USA" },
  { teamName: "Panthers", schoolName: "Florida International University", location: "Miami, Florida", conference: "C-USA" },
  { teamName: "Rams", schoolName: "Fordham University", location: "Bronx, New York", conference: "Patriot" },
  { teamName: "Leathernecks", schoolName: "Western Illinois University", location: "Macomb, Illinois", conference: "MVFC" },
  { teamName: "Furman Paladins", schoolName: "Furman University", location: "Greenville, South Carolina", conference: "SoCon" },
  { teamName: "Tigers", schoolName: "Grambling State University", location: "Grambling, Louisiana", conference: "SWAC" },
  { teamName: "Phoenix", schoolName: "Elon University", location: "Elon, North Carolina", conference: "CAA" },
  { teamName: "Bison", schoolName: "North Dakota State University", location: "Fargo, North Dakota", conference: "MVFC" },
  { teamName: "Crimson", schoolName: "Harvard University", location: "Cambridge, Massachusetts", conference: "Ivy" },
  { teamName: "Panthers", schoolName: "High Point University", location: "High Point, North Carolina", conference: "Big South" },
  { teamName: "Bears", schoolName: "University of Northern Colorado", location: "Greeley, Colorado", conference: "Big Sky" },
  { teamName: "Cougars", schoolName: "College of Charleston", location: "Charleston, South Carolina", conference: "CAA" },
  { teamName: "Jaguars", schoolName: "Southern University", location: "Baton Rouge, Louisiana", conference: "SWAC" },
  { teamName: "Eagles", schoolName: "North Carolina Central University", location: "Durham, North Carolina", conference: "MEAC" },
  { teamName: "Sycamores", schoolName: "Indiana State University", location: "Terre Haute, Indiana", conference: "MVFC" },
  { teamName: "Cyclones", schoolName: "Iowa State University", location: "Ames, Iowa", conference: "Big 12" },
  { teamName: "Dolphins", schoolName: "Jacksonville University", location: "Jacksonville, Florida", conference: "Pioneer" },
  { teamName: "Gamecocks", schoolName: "Jacksonville State University", location: "Jacksonville, Alabama", conference: "CUSA" },
  { teamName: "Dukes", schoolName: "James Madison University", location: "Harrisonburg, Virginia", conference: "Sun Belt" },
  { teamName: "Hatters", schoolName: "Stetson University", location: "DeLand, Florida", conference: "Pioneer" },
  { teamName: "Panthers", schoolName: "Prairie View A&M University", location: "Prairie View, Texas", conference: "SWAC" },
  { teamName: "Owls", schoolName: "Kennesaw State University", location: "Kennesaw, Georgia", conference: "ASUN" },
  { teamName: "Bisons", schoolName: "Lipscomb University", location: "Nashville, Tennessee", conference: "ASUN" },
  { teamName: "Wildcats", schoolName: "University of New Hampshire", location: "Durham, New Hampshire", conference: "CAA" },
  { teamName: "Green Wave", schoolName: "Tulane University", location: "New Orleans, Louisiana", conference: "AAC" },
  { teamName: "Demons", schoolName: "Northwestern State University", location: "Natchitoches, Louisiana", conference: "Southland" },
  { teamName: "Bears", schoolName: "Mercer University", location: "Macon, Georgia", conference: "SoCon" },
  { teamName: "RedHawks", schoolName: "Southeast Missouri State University", location: "Cape Girardeau, Missouri", conference: "OVC" },
  { teamName: "Lakers", schoolName: "Grand Valley State University", location: "Allendale, Michigan", conference: "GLIAC" },
  { teamName: "Black Bears", schoolName: "University of Maine", location: "Orono, Maine", conference: "CAA" },
  { teamName: "Golden Eagles", schoolName: "University of Minnesota Crookston", location: "Crookston, Minnesota", conference: "NSIC" },
  { teamName: "Redhawks", schoolName: "Miami University", location: "Oxford, Ohio", conference: "MAC" },
  { teamName: "Spartans", schoolName: "Michigan State University", location: "East Lansing, Michigan", conference: "Big Ten" },
  { teamName: "Bison", schoolName: "University of Manitoba", location: "Winnipeg, Manitoba", conference: "Canada West" },
  { teamName: "Racers", schoolName: "Murray State University", location: "Murray, Kentucky", conference: "MVFC" },
  { teamName: "Bison", schoolName: "Howard University", location: "Washington, D.C.", conference: "MEAC" },
  { teamName: "Delta Devils", schoolName: "Mississippi Valley State University", location: "Itta Bena, Mississippi", conference: "SWAC" },
  { teamName: "Mocs", schoolName: "University of Tennessee at Chattanooga", location: "Chattanooga, Tennessee", conference: "SoCon" },
  { teamName: "Privateers", schoolName: "University of New Orleans", location: "New Orleans, Louisiana", conference: "Southland" },
  { teamName: "Flames", schoolName: "Liberty University", location: "Lynchburg, Virginia", conference: "ASUN" },
  { teamName: "Monarchs", schoolName: "Old Dominion University", location: "Norfolk, Virginia", conference: "Sun Belt" },
  { teamName: "Bobcats", schoolName: "Montana State University", location: "Bozeman, Montana", conference: "Big Sky" },
  { teamName: "Grizzlies", schoolName: "University of Montana", location: "Missoula, Montana", conference: "Big Sky" },
  { teamName: "Aggies", schoolName: "North Carolina A&T State University", location: "Greensboro, North Carolina", conference: "CAA" },
  { teamName: "Pirates", schoolName: "Hampton University", location: "Hampton, Virginia", conference: "CAA" },
  { teamName: "Big Green", schoolName: "Dartmouth College", location: "Hanover, New Hampshire", conference: "Ivy" },
  { teamName: "Blue Hose", schoolName: "Presbyterian College", location: "Clinton, South Carolina", conference: "Pioneer" },
  { teamName: "Bulls", schoolName: "University of Buffalo", location: "Buffalo, New York", conference: "MAC" },
  { teamName: "Golden Bears", schoolName: "Morgan State University", location: "Baltimore, Maryland", conference: "MEAC" },
  { teamName: "Lions", schoolName: "Columbia University", location: "New York, New York", conference: "Ivy" },
  { teamName: "Pioneers", schoolName: "Sacred Heart University", location: "Fairfield, Connecticut", conference: "NEC" },
  { teamName: "Lions", schoolName: "Southeastern Louisiana University", location: "Hammond, Louisiana", conference: "Southland" },
  { teamName: "Bulldogs", schoolName: "Samford University", location: "Birmingham, Alabama", conference: "SoCon" },
  { teamName: "Mean Green", schoolName: "University of North Texas", location: "Denton, Texas", conference: "AAC" },
  { teamName: "Ospreys", schoolName: "University of North Florida", location: "Jacksonville, Florida", conference: "ASUN" },
  { teamName: "Quakers", schoolName: "University of Pennsylvania", location: "Philadelphia, Pennsylvania", conference: "Ivy" },
  { teamName: "Bobcats", schoolName: "Ohio University", location: "Athens, Ohio", conference: "MAC" },
  { teamName: "Skyhawks", schoolName: "University of Tennessee at Martin", location: "Martin, Tennessee", conference: "OVC" },
  { teamName: "Tigers", schoolName: "Tennessee State University", location: "Nashville, Tennessee", conference: "OVC" },
  { teamName: "Thunderbirds", schoolName: "Southern Utah University", location: "Cedar City, Utah", conference: "UAC" },
  { teamName: "Spartans", schoolName: "University of South Carolina Upstate", location: "Spartanburg, South Carolina", conference: "Big South" },
  { teamName: "Gamecocks", schoolName: "South Carolina State University", location: "Orangeburg, South Carolina", conference: "MEAC" },
  { teamName: "Spiders", schoolName: "University of Richmond", location: "Richmond, Virginia", conference: "CAA" },
  { teamName: "Buccaneers", schoolName: "East Tennessee State University", location: "Johnson City, Tennessee", conference: "SoCon" },
  { teamName: "Bears", schoolName: "Central Arkansas University", location: "Conway, Arkansas", conference: "UAC" },
  { teamName: "Aggies", schoolName: "Utah State University", location: "Logan, Utah", conference: "Mountain West" },
  { teamName: "Highlanders", schoolName: "University of California, Riverside", location: "Riverside, California", conference: "Big West" },
  { teamName: "Tigers", schoolName: "Towson University", location: "Towson, Maryland", conference: "CAA" },
  { teamName: "Crusaders", schoolName: "Valparaiso University", location: "Valparaiso, Indiana", conference: "Pioneer" },
  { teamName: "Terriers", schoolName: "Wofford College", location: "Spartanburg, South Carolina", conference: "SoCon" },
  { teamName: "Sharks", schoolName: "Long Island University", location: "Brooklyn, New York", conference: "NEC" },
  { teamName: "Bulldogs", schoolName: "Yale University", location: "New Haven, Connecticut", conference: "Ivy" },
  { teamName: "Penguins", schoolName: "Youngstown State University", location: "Youngstown, Ohio", conference: "MVFC" }
];